language: cpp

dist: trusty
sudo: required

before_install:
  - sudo apt-get update -qq

install:
  # TRAVIS_BUILD_DIR is set to where the source code is checked
  # out (ie it assumes in-source build)
  - JSON_INSTALL_DIR="${TRAVIS_BUILD_DIR}/../include/nlohmann"
  - mkdir -p "${JSON_INSTALL_DIR}"
  - travis_retry wget --quiet -O "${JSON_INSTALL_DIR}/json.hpp" https://raw.githubusercontent.com/nlohmann/json/v2.0.6/src/json.hpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: CXX_=clang++-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: CXX_=clang++-3.8
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      env: CXX_=clang++-3.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CXX_=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX_=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CXX_=g++-6

script:
  - cmake --version
  - CXX=${CXX_:-${CXX}}
  - ${CXX} --version
  - SOURCE_DIR="${TRAVIS_BUILD_DIR}"
  - BUILD_DIR="${TRAVIS_BUILD_DIR}/../build"
  - mkdir "${BUILD_DIR}"
  - cd "${BUILD_DIR}"
  - cmake -DJSON_FOR_MODERN_CXX_INCLUDE_DIR:PATH="${TRAVIS_BUILD_DIR}/../include" -DBUILD_SHARED_LIBS:BOOL=ON "${SOURCE_DIR}"
  - make
