language: cpp

dist: trusty
sudo: required

install:
  # TRAVIS_BUILD_DIR is set to where the source code is checked
  # out (ie it assumes in-source build)
  - JSON_INSTALL_DIR="${TRAVIS_BUILD_DIR}/../include/nlohmann"
  - mkdir -p "${JSON_INSTALL_DIR}"
  - travis_retry wget --quiet -O "${JSON_INSTALL_DIR}/json.hpp" https://raw.githubusercontent.com/nlohmann/json/v2.0.7/src/json.hpp

  - GO_IPFS_DIR="${TRAVIS_BUILD_DIR}/../go-ipfs"
  - GO_IPFS_ARCHIVE_BASENAME="go-ipfs_v0.4.4_linux-amd64.tar.gz"
  - GO_IPFS_ARCHIVE_FULLPATH="${GO_IPFS_DIR}/${GO_IPFS_ARCHIVE_BASENAME}"
  - GO_IPFS_CMD="${GO_IPFS_DIR}/go-ipfs/ipfs"
  - |
    if [ ! -e "${GO_IPFS_ARCHIVE_FULLPATH}" ] ; then
      mkdir -p "${GO_IPFS_DIR}"
      travis_retry wget --quiet -O "${GO_IPFS_ARCHIVE_FULLPATH}" "https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.4/${GO_IPFS_ARCHIVE_BASENAME}"
    fi
  - |
    if [ ! -x "${GO_IPFS_CMD}" ] ; then
      tar -C "${GO_IPFS_DIR}" -vzxf "${GO_IPFS_ARCHIVE_FULLPATH}"
    fi

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/../go-ipfs

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get update -qq
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: CXX_=clang++-3.7
    - os: linux
      before_install:
        - sudo apt-get update -qq
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: CXX_=clang++-3.8
      after_success:
        - export IPFS_PATH="${TRAVIS_BUILD_DIR}/../ipfs-repository"
        - ${GO_IPFS_CMD} init
        - ${GO_IPFS_CMD} daemon > ipfs_daemon.out 2>&1 &
        - |
          while ! grep -i 'Daemon is ready' ipfs_daemon.out ; do
            echo "$(date) Waiting for ipfs daemon to start..."
            sleep 1
          done
        - CTEST_OUTPUT_ON_FAILURE=1 make test
        - ret=$?
        - killall ${GO_IPFS_CMD}
        - echo ${ret}
        - exit ${ret}
    - os: linux
      before_install:
        - sudo apt-get update -qq
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CXX_=g++-4.9
    - os: linux
      before_install:
        - sudo apt-get update -qq
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX_=g++-5
    - os: linux
      before_install:
        - sudo apt-get update -qq
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CXX_=g++-6
    - os: osx
      osx_image: xcode8

script:
  - cmake --version
  - CXX=${CXX_:-${CXX}}
  - ${CXX} --version
  - SOURCE_DIR="${TRAVIS_BUILD_DIR}"
  - BUILD_DIR="${TRAVIS_BUILD_DIR}/../build"
  - mkdir "${BUILD_DIR}"
  - cd "${BUILD_DIR}"
  - cmake -DJSON_FOR_MODERN_CXX_INCLUDE_DIR:PATH="${TRAVIS_BUILD_DIR}/../include" -DBUILD_SHARED_LIBS:BOOL=ON "${SOURCE_DIR}"
  - make
